### PR TITLE
Add flake support

### LINKED ISSUE #76: [feature]: add flake.nix to package project in Nix
**Is your feature request related to a problem? Please describe.**
It would be nice if there was a `flake.nix` added to the project so that `tgt` can be added as a Nix package in Nix systems.

**Describe the solution you'd like**
A `flake.nix` file added to the project root.

**Describe alternatives you've considered**
There are no alternatives other than compiling the project for the current system.

**Additional context**
I have already tried packaging the project into Nix, but the main hurdle is with copying the config files to `$HOME/.tgt/conifg` since Nix doesn't allow changing other directories except for a few allowed ones such as current source dir and installation dir.

AFAICT the only solution is to make the `tgt` app itself generate these config files where ever necessary in case they are missing on launch.

### PR DESCRIPTION
**Pull request by DontEatOreo**
Closes #76 

Context: https://github.com/FedericoBruzzone/tgt/pull/77#issuecomment-2440334310

About these lines:

```nix
src = pkgs.fetchFromGitHub {
  owner = "FedericoBruzzone";
  repo = "tgt";
  rev = "470b6052dd66ff55f6039bbf940902f503fb67e2";
  sha256 = "sha256-VO1KdAgx0hLYEegyotBO8eLPbA33KKEoanZRLqQCiHI=";
};
```

The reason I'm pinning to a specific commit is that:

1. We're using `cargoHash`, which produces an exact hash of all the dependencies *(plus other factors, e.g., `pname`)*, so any changes to the `Cargo.lock` will result in a completely different hash and be unable to build the flake.
2. The `flake.nix` relies on a patch to fix `build.rs` in order to work properly on Nix
3. I can only guarantee the functioning of the program and the successful build of that program for that commit right now, so leaving it as `src = ./.;` would just mean it breaks in the future and breaks the reproducible "promise"

I do not plan on adding support for a `devShell` as I don't know how to write Rust code or have any meaningful knowledge in Rust; thus, I can't guarantee a proper `devShell` experience

Although I would imagine anyone familiar with Nix who wants to develop this project would most likely have the know-how to add `devShell` support themselves better than I could.

Currently, it builds and runs on `x86_64-linux` and `aarch64-darwin`. I don't own an `aarch64-linux` or `x86_64-darwin` machine, but theoretically, they shouldn't have any issues either.

### CODE REVIEW

**Review by FedericoBruzzone — APPROVED** [review]

**Comment by FedericoBruzzone** [comment]
Wow! Thanks for your PR!

> 1. We're using cargoHash, which produces an exact hash of all the dependencies (plus other factors, e.g., pname), so any changes to the Cargo.lock will result in a completely different hash and be unable to build the flake.

That's Ok!

> 2. The flake.nix relies on a patch to fix build.rs in order to work properly on Nix

That's Ok, but I will try to release a new version with some bug fix. In that case, can I ping you in order you do a new small PR to remove the patch?

> 3. I can only guarantee the functioning of the program and the successful build of that program for that commit right now, so leaving it as src = ./.; would just mean it breaks in the future and breaks the reproducible "promise"

Since I am not yet a `nix` user, what we should do to improve this mechanism?

> Although I would imagine anyone familiar with Nix who wants to develop this project would most likely have the know-how to add devShell support themselves better than I could.

Can you open an Issue to track it?


Now, I was wondering how can `tgt` runs if `~/.tgt/config` is empty. Can you provide me an answer :'D ?

**Comment by DontEatOreo** [comment]
> That's Ok, but I will try to release a new version with some bug fix. In that case, can I ping you in order you do a new small PR to remove the patch?

Yes! I will be glad to remove the patch

> Since I am not yet a nix user, what we should do to improve this mechanism?

Sadly, you can't do much about this. You can ping me, when you want the flake updated though. Usually, unless something fundamentally changed (like the new system dependencies or changes to how the program is built), the only thing that will need to be changed for `flake.nix` to be up to date will be to bump the `rev` and `hash`

One automate solution could be for GitHub *(using CI/CD)* to try to update the `hash` and `rev` and make a new commit for the flake if just updating the `rev` and `hash` is enough for that new commit

> Can you open an Issue to track it?

I could, but I see it as kind of useless. Pretty much 99% of the consumers/users of this flake will be adding it to their own flake via inputs and then straight into their system packages or just running `nix run github:FedericoBruzzone/tgt`

> Now, I was wondering how can `tgt` runs if `~/.tgt/config` is empty. Can you provide me an answer :'D ?

***Well, you can't!*** I simply create the `~/.tgt/config` path manually *(after building tgt)* and copied the files from `./config`. Currently I'm not using any modules for this `flake.nix`, so I can't tamper with the "outside world"

**Comment by FedericoBruzzone** [comment]
> Yes! I will be glad to remove the patch

Again, thank you so much!

> I could, but I see it as kind of useless. Pretty much 99% of the consumers/users of this flake will be adding it to their own flake via inputs and then straight into their system packages or just running nix run github:FedericoBruzzone/tgt

Ok, then no problem :D 

> Well, you can't! I simply create the ~/.tgt/config path manually (after building tgt) and copied the files from ./config. Currently I'm not using any modules for this flake.nix, so I can't tamper with the "outside world"

Ok, perfect. So I think that we should add to the README this information, what you think about that?

**Comment by FedericoBruzzone** [comment]
Thanks for your contribution!

**Pull request merged**
